export { default as authRoutes } from './auth.js'
export { default as productRoutes } from './products.js'
export { default as cartRoutes } from './cart.js'
export { default as wishlistRoutes } from './wishlist.js'
export { default as orderRoutes } from './orders.js'